# Generated by Django 5.0.3 on 2024-04-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Product', '0002_category_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField()),
                ('amount', models.FloatField()),
                ('status', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(to='Product.product')),
            ],
        ),
    ]
