# Generated by Django 5.0.3 on 2024-04-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0003_alter_order_user'),
        ('Product', '0003_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='Product.orderitem'),
        ),
    ]
